### ISSUE TITLE
concommand:Remove() errors

### ISSUE THREAD

**Issue by xaviergmail** [danielga/gm_concommandx#1]
Running a _non-modified unsupported build_,  latest SRCDS on Windows 10
```
version
Protocol version 24
Exe version 18.12.05 (garrysmod)
Exe build: 15:58:05 Dec 15 2018 (7343) (4000)
```

**I already did concommand.Get("status"):SetName("_status")**

![](https://xavie.ru/i/35zV08Q.png)

**Comment by danielga** [comment]
I believe this is now fixed on master.
